[package]
name = "lockbox"
edition = "2018"
version = "0.1.0"
authors = ["application-services <application-services@mozilla.com>"]
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
fxa-client = { path = "../../components/fxa-client" }
logins_ffi = { path = "../../components/logins/ffi" }
rc_log_ffi = { path = "../../components/rc_log" }
viaduct = { path = "../../components/viaduct", default-features = false }
